version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34

    ports:
      - '4466:4466'
    depends_on:
      - mysql-db
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: prisma
            
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
